apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJhM0p2YjNScGVEcG5hSEJmV2tSSWJWWlBaMlJ5UjFZMmQyMTZZVE00Y2tOeE9VZDVRWFJ6VG5Nek0zaExVbHBCIgoJCX0KCX0sCgkiY3JlZHNTdG9yZSI6ICJkZXNrdG9wIiwKCSJjdXJyZW50Q29udGV4dCI6ICJkZXNrdG9wLWxpbnV4Igp9
type: kubernetes.io/dockerconfigjson
